### ISSUE TITLE
digdag serverで実行した時に、存在するはずのsql fileが見つからない

### ISSUE THREAD

**Issue by hiro-hori** [flinters/digdag_operator_snowflake#12]
```
2021-07-07 09:27:29.450 +0000 [INFO] (2336321@[0:debug_hori]+snow+load) io.digdag.core.agent.OperatorManager: snow>: select1.sql
2021-07-07 09:27:29.539 +0000 [ERROR] (2336321@[0:debug_hori]+snow+load) io.digdag.core.agent.OperatorManager: Task failed with unexpected error: select1.sql (No such file or directory)
java.io.FileNotFoundException: select1.sql (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at scala.io.Source$.fromFile(Source.scala:94)
	at scala.io.Source$.fromFile(Source.scala:79)
	at scala.io.Source$.fromFile(Source.scala:57)
	at dev.hiro_hori.digdag_operator_snowflake.SnowOperator.runTask(SnowOperator.scala:26)
	at io.digdag.util.BaseOperator.run(BaseOperator.java:35)
	at io.digdag.core.agent.OperatorManager.callExecutor(OperatorManager.java:365)
	at io.digdag.server.metrics.DigdagTimedMethodInterceptor.invokeMain(DigdagTimedMethodInterceptor.java:58)
	at io.digdag.server.metrics.DigdagTimedMethodInterceptor.invoke(DigdagTimedMethodInterceptor.java:31)
	at io.digdag.core.agent.OperatorManager.runWithWorkspace(OperatorManager.java:298)
	at io.digdag.server.metrics.DigdagTimedMethodInterceptor.invokeMain(DigdagTimedMethodInterceptor.java:58)
	at io.digdag.server.metrics.DigdagTimedMethodInterceptor.invoke(DigdagTimedMethodInterceptor.java:31)
	at io.digdag.core.agent.OperatorManager.lambda$runWithHeartbeat$2(OperatorManager.java:151)
	at io.digdag.core.agent.ExtractArchiveWorkspaceManager.withExtractedArchive(ExtractArchiveWorkspaceManager.java:77)
	at io.digdag.core.agent.OperatorManager.runWithHeartbeat(OperatorManager.java:149)
	at io.digdag.server.metrics.DigdagTimedMethodInterceptor.invokeMain(DigdagTimedMethodInterceptor.java:58)
	at io.digdag.server.metrics.DigdagTimedMethodInterceptor.invoke(DigdagTimedMethodInterceptor.java:31)
	at io.digdag.core.agent.OperatorManager.run(OperatorManager.java:132)
	at io.digdag.server.metrics.DigdagTimedMethodInterceptor.invokeMain(DigdagTimedMethodInterceptor.java:58)
	at io.digdag.server.metrics.DigdagTimedMethodInterceptor.invoke(DigdagTimedMethodInterceptor.java:31)
	at io.digdag.core.agent.MultiThreadAgent.lambda$null$0(MultiThreadAgent.java:132)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by so-tomoshira** [comment]
@hiro-hori 最初のdigをベースにディレクトリ走査してそうですね。なので、ファイルパスを変えればファイルを見つける事自体は可能でした。

**Comment by hiro-hori** [comment]
最小再現コード

```sh_session
$ ls example.dig example.sql
example.dig     example.sql
$ cat example.dig
_export:
    plugin:
        repositories:
            - com.github.hiro-hori:digdag_operator_snowflake:v0.1.2
        dependencies:
            - dev.hiro-hori:digdag-operator-snowflake_2.13:0.1.0-SNAPSHOT
    snow:
        # host: zz99999.us-east-99.aws.snowflakecomputing.com
        host: 😀😀😀😀😀.ap-northeast-1.aws.snowflakecomputing.com
        # role: sysadmin
        # user: snow_user
        user: 😀😀😀😀😀_user
        warehouse: compute_wh
        # schema: public
        session_unixtime_sql_variable_name: session_time

+run_task:
    snow>: example.sql
$ cat example.sql
SELECT
   123234 as c,
   $session_time as session_time
$
```
